### PR TITLE
Add benchmarks

### PR DESCRIPTION
**Pull request by Kolaru**
This PR add benchmarks using `PkgBenchmark.jl`. 

These benchmarks are based on the Smiley and Chun examples used in tests and the Dietmar and Ratz example functions used in the `/perf` folder. I only added a subset of the benchmark performed in the `/perf` folder to keep the benchmark time reasonnable, while having representative benchmarks.

Of course, I will gladly add anything that seems missing.

This was tested with `PkgBenchmark.jl` `v0.2.0`.

No special infrastructure are added by this PR to automatically benchmark the package, as I don't know if it is worth for now (or will ever be).

I see this PR as usefull to the progress of #97, as it will facilitate discussion about its performance consequences.

### CODE REVIEW

**Comment by Kolaru** [comment]
Codecov gets very confused but I don't know why. Putting back tests in their initial form does not help.

**Comment by Kolaru** [comment]
Build is failing because some tests in `newton1d.jl` fail due to the latest master of `IntervalArithmetic.jl`. They are fixed in #93 though, if needed I could submit a separate hotfix though.

**Comment by Kolaru** [comment]
Unless some more benchmark are requested I thing this is ready.

**Comment by dpsanders** [comment]
Thanks a lot!

**Pull request merged**
