### PR TITLE
Allow using IntervalArithmetic.jl v0.17

### PR DESCRIPTION
**Pull request by lbenet**

### CODE REVIEW

**Comment by lbenet** [comment]
@dpsanders Should we patch a new minor version? Part of the problem in https://github.com/JuliaIntervals/TaylorModels.jl/pull/71 seems related to this...

**Comment by dpsanders** [comment]
Isn't a new patch version enough?

Tests seem to be failing.

**Comment by lbenet** [comment]
Yes, my mistake, indeed, a patch version is enough...

I'll take a look on the tests that are failing...

**Comment by lbenet** [comment]
@dpsanders Tests are passing now and the patch version in Project.toml has been updated to release a new version. Shall we merge this?

**Comment by dpsanders** [comment]
Thanks a lot!

**Pull request merged**
