### PR TITLE
Refresh documentation

### LINKED ISSUE #61: Document new roots syntax and iterator interface.
- [ ] Syntax for `roots`
- [ ] Iterator interface
- [ ] Remove old docs

### PR DESCRIPTION
**Pull request by Kolaru**
This fix #61. Along the way I end up rewriting or reformulating most of the documentation. The upside of this is that now it should fully be up-to-date.

Edit: also I hope you don't mind the introduction of a little bit of Python for the documentation, I haven't had the courage (yet ?) to learn other plotting library than Matplotlib.

### CODE REVIEW

**Comment by dpsanders** [comment]
This is fantastic, thanks!
I didn't see the Python graphics. I would prefer to use `Plots.jl`, but that can come later.

There are a few spelling mistakes. What is the best way for me to correct them? Probably I should just add a commit to your PR somehow.

**Comment by Kolaru** [comment]
You should normally have write access by default to the branch corresponding to a PR in my fork (if this is really what "Allow edits from maintainers" means).

Anyway I've invited you as a collaborator to my fork so you should be able to push commit directly.

The python plot I was talking about is in the new [README.md](https://github.com/Kolaru/IntervalRootFinding.jl/blob/documentation/README.md).

**Comment by dpsanders** [comment]
Sorry (once again) in the delay in getting to this. That plot should be "easy" to do in Plots.jl, but I haven't sat down to do it; I also lost track of the fact that I was going to correct a few things here. Hopefully in a couple of days.

**Comment by dpsanders** [comment]
I'm getting 
```
>     git push Kolaru Kolaru-documentation
fatal: remote error:
  You can't push to git://github.com/Kolaru/IntervalRootFinding.jl.git
  Use https://github.com/Kolaru/IntervalRootFinding.jl.git
```

**Comment by dpsanders** [comment]
This is really fantastic -- thanks so much for doing this! Great explanations.

I have pushed a branch `Kolaru-documentation` to the main repo. You should be able to pull that into your branch somehow to update this PR?

**Comment by dpsanders** [comment]
Clarification: The branch I pushed has some updates I made to the English / to make some things a bit clearer or more precise.

**Comment by Kolaru** [comment]
Thanks for the review! I've merged your changes so this PR is now up to date.

As for why you wasn't able to push directly to my repo or this PR, I fear my git knowledge is too limited to help.

**Comment by dpsanders** [comment]
Thanks a lot!

**Comment by Kolaru** [comment]
@dpsanders Don't forget to deploy the doc (I would do it myself, if I didn't fear to screw something up).

**Comment by dpsanders** [comment]
Now we just have to make sure the docs build correctly.

**Comment by dpsanders** [comment]
The deployment is supposed to be automatic but I'm not sure of the process. I believe @lbenet may be able to help.

**Pull request merged**
