### PR TITLE
Add promotion_rule to handle promotion involving Dual

### PR DESCRIPTION
**Pull request by lbenet**
Related to https://github.com/JuliaIntervals/IntervalArithmetic.jl/pull/13

### CODE REVIEW

**Comment by lbenet** [comment]
This is an alternative to #12...

**Comment by dpsanders** [comment]
Are these actually necessary, though? The package seems to work fine without any of these promotion rules.

**Comment by lbenet** [comment]
I don't recall why we needed them at all. So I'll close this and we check #12.

**Comment by dpsanders** [comment]
I think we needed them because of some ambiguities on Julia 0.4. But it seems they were only "potential" ambiguities that were never actually encountered!

**Pull request closed without merging**
