### PR TITLE
Add Interval as constant

### PR DESCRIPTION
**Pull request by lbenet**
Tests are failing after cloning because `Interval` is not being recognized. I simply solve this by adding it as a `const`

### CODE REVIEW

**Comment by dpsanders** [comment]
Thanks, LGTM. Not sure what's up with the `bisect` function.

**Comment by lbenet** [comment]
The problem is not `bisect` itself, but using for that test the `a..b` notation, which uses `prevfloat(a)` if `a` is not an integer and something similar for `b` with `nextfloat(b)`. 

That's the reason we get:
```
julia> using IntervalArithmetic

julia> 0.5..0.5
[0.499999, 0.500001]

julia> inf(ans), sup(ans)
(0.49999999999999994, 0.5000000000000001)
```

`bisect` (correctly) returns a tuple of intervals constructed with `Interval`.

I just submitted a new commit which fixes the test.

**Comment by lbenet** [comment]
Tests pass now in Julia 0.6, but fail in Julia 0.7. 

Any ideas?

**Comment by dpsanders** [comment]
No, sorry, it's not clear what the problem is.

Can we use FemtoCleaner to get rid of all the deprecations?

**Comment by lbenet** [comment]
We should certainly use it. Perhaps #14 and #17 should be merged as well.

**Comment by lbenet** [comment]
Restarted failing travis jobs on nightly. Let's see if https://github.com/JuliaIntervals/IntervalArithmetic.jl/issues/93 is related...

**Comment by lbenet** [comment]
Closing, since it is currently [reexported](https://github.com/JuliaIntervals/IntervalArithmetic.jl/pull/96)

**Pull request closed without merging**
