### PR TITLE
Fix docs deployment (travis)

### LINKED ISSUE #126: Fix docs deployment

### PR DESCRIPTION
**Pull request by lbenet**
Fixes #126

### CODE REVIEW

**Comment by lbenet** [comment]
@dpsanders @Kolaru I think this is ready to be merged, which is actually the real check. Travis output [for the docs](https://travis-ci.org/JuliaIntervals/IntervalRootFinding.jl/jobs/525377292#L511) seems to have run as it should.

**Comment by dpsanders** [comment]
Thanks a lot!

**Comment by lbenet** [comment]
It still takes some time for the docs to be deployed and ready...

**Comment by lbenet** [comment]
@dpsanders While the docs deployment seems to have gone ok, there seems to be a problem with the `DOCUMENTER_KEY` (so the new docs are not yet there); see [here](https://travis-ci.org/JuliaIntervals/IntervalRootFinding.jl/jobs/525393345#L540). 

I'll try to fix this.

**Comment by lbenet** [comment]
Restarted travis job to see if it works now...

**Comment by lbenet** [comment]
Now it worked

**Comment by dpsanders** [comment]
Fantastic, thanks a lot for sorting this out!
Now we just have to do the same with the other packages.

**Comment by lbenet** [comment]
Ok. I'll check each one, one at a time :-)

**Pull request merged**
